[package]
name = "hotcorners"
version = "0.1.2"
authors = ["Tim Roberts <tim@timroberts.dev>"]
edition = "2021"
license = "GPL-3.0-only"
description = "A small hot corners implementation for Windows 10/11"
repository = "https://github.com/timrobertsdev/hotcorners"
keywords = ["windows", "hotcorners"]
categories = ["command-line-utilities"]

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
windows = "0.21"

[build-dependencies]
windows = "0.21"
